### ISSUE TITLE
Script not load the data

### ISSUE THREAD

**Issue by gravino81** [BobRay/Orphans#3]
Hello Bob, 
my site is  large site and the Extra not load data in components page, I activated and execute the snippet and have the data, but in Extra nothing yet and have this errors: 

[2019-01-22 09:34:52] (ERROR @ /home/www/public_html/modx/core/components/orphans/processors/mgr/getlist.class.php : 36) PHP warning: require_once(c:/xampp/htdocs/addons/assets/mycomponents/orphans/core/components/orphans/model/orphans/orphans.class.php): failed to open stream: File or directory does not exist

Orphans version 1.2.0-pl
Modx version 2.7.0-pl

**Comment by BobRay** [comment]
Definitely a bug.  Try changing that line in getlist.class.php to:

`require_once MODX_CORE_PATH . 'components/orphans/model/orphans/orphans.class.php';`

**Comment by gravino81** [comment]
I change the line, I no longer have the error. Now in the page where I inserted the snippet can see the list of elements orphans, but in components page not load the data anyway.

**Comment by BobRay** [comment]
Upgrade to Version 1.2.1, manually delete all files in the core/cache directory. You may also have to clear your browser cache and cookies.

**Comment by gravino81** [comment]
Good job, now if you click on Search for Orphan load the data correctly!

**Comment by BobRay** [comment]
Thanks for letting me know. :)
